<?php
$dictionar = array
(
    'add-on=[plugin]',                                               null,
#    'antialiasing=',                                                 null,
    'appendix=anexă',                                                null,
    'applet=miniaplicație',                                          null,
    'background=fundal',                                             null,
    'backslash=bară oblică inversă',                                 null,
#    'backspace=',                                                    null,
    'backup=rezervă,copie de rezervă',                               null,
    'a bana=a interzice',                                            null,
    'bandwidth=lățime de bandă',                                     null,
    'bannat=interzis,blocat',                                        'Am fost <strong>banat</strong> de pe site-ul ăla.=Am fost <strong>interzis</strong> pe situl ăla.',
    'batch=lot',                                                     null,
    'beep=bip',                                                      null,
    'blog=jurnal,jurnal de internet',                                null,
    'bold=aldin,îngroșat',                                           null,
    'bookmark=marcaj,semn de carte',                                 null,
    'a boot-a=a porni',                                              '<strong>Boot-ează</strong> sistemul de pe CD-ul ăsta.=<strong>Pornește</strong> sistemul de pe discul ăsta.',
    'brand=marcă',                                                   null,
    'browser=navigator',                                             'Ce application folosesti ca sa <strong>browser-esti</strong> Internet-ul?=Ce program folosești ca să <strong>naveghezi</strong> internetul?',
    'buffer=tampon,memorie tampon',                                  null,
    'byte=octet',                                                    null,
#    'cache=',                                                        null,
    'card=cartelă',                                                  null,
    'CD=disc,disc compact,DC',                                       null,
#    'chat=',                                                         null,
    'a check-ui=a bifa',                                             null,
    'click=clic',                                                    'Nu se aude <strong>clickul</strong> la mouseul ăsta.=Nu se aude <strong>clicul</strong> la șoricelul ăsta.',
    'a clicka=a apasa',                                              'Trebuie să <strong>clickezi</strong> pe bătănul ăsta când apare windowul.=Trebuie să <strong>apeși</strong> pe butonul ăsta când apare fereastra.',
#    'clipboard=',                                                    null,
#    'codec=',                                                        null,
    'comment=comentariu',                                            null,
    'computer=calculator',                                           'Am vazut Facultatea De Automatica Si <strong>Computer-e</strong>.=Am văzut Facultatea de Automatică și <strong>Calculatoare</strong>.',
    'cooler=ventilator',                                             null,
    'copy-paste=copiază-lipește',                                    null,
    'copyright=drept de autor',                                      null,
    'CPU=UCP',                                                       null,
#    'crash=',                                                        null,
    'database=bază de date',                                         null,
    'default=implicit',                                              null,
#    'design=',                                                       null,
#    'desktop=',                                                      null,
    'device=dispozitiv',                                             null,
    'disk=disc',                                                     null,
    'display=afișaj,ecran',                                          null,
    'domain=domeniu',                                                null,
    'double click=clic dublu',                                       null,
    'download=descarcă',                                             'Am <strong>download-at</strong> cu browser-ul de pe site-ul ăsta.=Am <strong>descărcat</strong> cu navigatorul de pe situl ăsta.',
    'drive=unitate',                                                 null,
#    'driver=',                                                       null,
    'encrypt=criptare',                                              null,
    'engine=motor',                                                  null,
#    'enter=',                                                        null,
    'feed=flux',                                                     null,
    'feedback=reacție,sugestie,comentariu',                          null,
    'file=fișier',                                                   null,
#    'firewall=',                                                     null,
    'folder=dosar',                                                  'Mută cele trei <strong>foldere</strong> la Recycle Bin.=Mută cele trei <strong>dosare</strong> la Gunoi.',
    'football=fotbal',                                               null,
    'footer=subsol',                                                 null,
    'footnote=notă de subsol',                                       null,
    'frame=cadru',                                                   null,
    'grid=grilă',                                                    null,
    'hard disk=disc dur',                                            null,
    'header=antet',                                                  null,
    'home folder=dosar personal',                                    null,
    'home page=pagină principală',                                   null,
    'icon=iconiță',                                                  null,
    'inch=țol',                                                      null,
    'italic=cursiv,înclinat',                                        null,
    'item=element',                                                  null,
    'keyboard=tastatură',                                            null,
    'laptop=calculator portabil',                                    null,
    'layer=strat',                                                   null,
    'link=legătură',                                                 'Da click pe <strong>linkul</strong> asta ca sa incepi downloadarea.=Apasă pe <strong>legătura</strong> asta ca să începi descărcarea.',
    'live=în direct',                                                null,
    'login=intrare,autentificare',                                   'Am dat <strong>login</strong> pe site-ul asta.=M-am <strong>autentificat</strong> pe situl ăsta.',
    'logout=ieșire,deautentificare',                                 'Am dat <strong>logout</strong> si am restartat computerul.=Am <strong>închis sesiunea</strong> și am repornit calculatorul.',
    'look=aspect,înfățișare',                                        'Ti-ai change-at <strong>look-ul</strong>?=Ți-ai schimbat <strong>aspectul</strong>?',
    'management=administrare,gestionare',                            null,
    'manager=administrator,gestionar',                               null,
    'mouse=șoricel,maus',                                            null,
    'netbook=[laptop]',                                              null,
    'next=înainte',                                                  null,
    'notebook=[laptop]',                                             null,
    'OK=bine',                                                       'Da click pe "<strong>OK</strong>".=Apasă pe „<strong>Bine</strong>“.',
    'okay=[OK]',                                                     null,
    'plain text=text simplu',                                        null,
    'a play-a=a reda',                                               null,
    'player=lector,redator',                                         null,
    'playlist=lista de redare',                                      null,
    'plugin=modul',                                                  null,
    'post=articol',                                                  'Cine a scris <strong>postul</strong> ăsta trebuia să se mai informeze.=Cine a scris <strong>articolul</strong> ăsta trebuia să se mai informeze.',
    'a post-a=a trimite,a adauga',                                   null,
    'a printa=a tipări',                                             'Cand dai <strong>print</strong> la cele two pagini la printăr?=Când <strong>tipărești</strong> cele două pagini la imprimantă.',
    'printer=imprimantă',                                            null,
    'provider=furnizor',                                             null,
    'rank=grad',                                                     null,
    'recycle bin=gunoi',                                             'Muvează cele 2 filezuri la <strong>Recycle Bin</strong>.=Mută cele două fișiere la <strong>Gunoi</strong>.',
    'refresh=împrospătare',                                          null,
    'a restarta=a reporni',                                          null,
    'restore=restaurare',                                            null,
    'review=recenzie',                                               null,
    'router=distribuitor',                                           null,
    'scan=scanare',                                                  null,
    'scanner=scaner',                                                null,
    'screen=ecran',                                                  null,
#    'script=',                                                       null,
    'a scroll-ui=a derula',                                          null,
    'service=stație/atelier de reparare și întreținere',             'Am dus masina la <strong>service</strong>.=Am dus mașina la <strong>reparat</strong>.',
    'settings=setari,preferințe,configurări',                        null,
    'sign-in=[login]',                                               null,
    'sign-out=[logout]',                                             null,
    'sing-up=înregistrare',                                          null,
    'site=sit,sait',                                                 null,
    'slash=bară oblică',                                             null,
#    'slide(delapowerpoint)=',                                        null,
#    'slot=',                                                         null,
    'software=soft,programe,logică',                                 'Un computer are partea hardware si partea <strong>software</strong>.=Un calculator are partea fizică și partea <strong>logică</strong>.',
    'space=spațiu',                                                  null,
    'stick=unitate USB',                                             null,
    'stream=flux',                                                   null,
    'streaming=difuzare în flux',                                    null,
    'string=șir,șir de caractere',                                   null,
    'tab=filă',                                                      'Da click pe al 2 <strong>tab</strong> sa vad ce se poate view-eva acolo.=Apasă pe a doua <strong>filă</strong> să văd ce se poate vedea acolo.',
    'tag=etichetă',                                                  null,
    'target=țintă',                                                  null,
    'task=sarcină',                                                  null,
    'taskbar=bară de activități',                                    null,
    'template=șablon,model',                                         null,
    'thread (forum)=discuție,fir de discuție',                       null,
    'thread (UCP)=fir,fir de execuție',                              null,
    'thumbnail=miniatură',                                           null,
    'topic=discuție,subiect',                                        'Nu are ce cauta <strong>topic-ul</strong> asta in forumul asta.=Nu are ce căuta <strong>discuția</strong> asta în forumul ăsta.',
    'torrent=torent',                                                null,
    'touchscreen=ecran tactil',                                      null,
#    'tracker=',                                                      null,
    'trend=tendință',                                                null,
    'tutorial=îndrumător,ghid (practic)',                            null,
    'tweaking=ajustare',                                             null,
    'update=actualizare',                                            null,
    'upgrade=actualizare majoră',                                    null,
    'user=utilizator',                                               null,
    'volume=volum',                                                  null,
    'wallpaper=imagine de fundal',                                   null,
    'web crawler=robot de indexare',                                 null,
    'webpage=pagină de internet',                                    null,
    'website=[site]',                                                null,
    'weekend=sfârșit de săptămână,sâmbătă și duminică',              null,
    'window=fereastră',                                              null,
    'wireless=fără fir',                                             null,
    'WTF=CPM',                                                       '<strong>WTF</strong> happened?=<strong>CPM</strong> s-a-ntâmplat?',
);
?>
